<?php

use Illuminate\Database\Eloquent\SoftDeletingTrait; // <-- This is required


class InspectorDetails extends Eloquent
{
	use SoftDeletingTrait;
	
	protected $table = 'inspectordetails';

	protected $fillable = [
	  'vehicle_id',
	  'cust_id',
	  'name',
	  'sno',
	  'chasisno',
	  'model',
	  'enginemodel',
	  'modelname',
	  'make',
	  'engineno',
	  'enginecc',
	  'yofr',
	  'yom',
	  'bodycolor',
	  'mileage',
	  'odometer',
	  'fueltype',
	  'teeringwheel',
	  'weight',
	  'frontweight',
	  'rearweight',
	  'location',
	  'inspectorid',
	  'accellerationstatuss',
	  'co',
	  'costatus',
	  'abnormalbrake',
	  'abnormalbrakestatus',
	  'hc',
	  'hcstatus',
	  'diesel',
	  'sidslipinout',
	  'sidslipinoutstatus',
	  'normalnoise',
	  'normalnoisestatus',
	  'badnoise1st',
	  'badnoise2nd',
	  'badnoisestatus',
	  'badnoiseaverage',
	  'luminancer',
	  'luminancerstatus',
	  'luminancel',
	  'luminancelstatus',
	  'attachmentr',
	  'attachmentrstatus',
	  'attachmentl',
	  'attachmentlstatus',
	  'opticalr',
	  'opticalrstatus',
	  'opticall',
	  'opticallstatus',
	  'opticalaxisr',
	  'opticalaxisrstatus',
	  'opticalaxisl',
	  'opticalaxislstatus',
	  'engineresult',
	  'wheelbearingresult',
	  'funbeltresult',
	  'springsresult',
	  'batteryresult',
	  'absorbersresult',
	  'mastercylresult',
	  'suspensionresult',
	  'carburretorresult',
	  'torueresult',
	  'fuelpipesresult',
	  'gearboxresult',
	  'injpumpresult',
	  'steeringrodresult',
	  'wirenarnessresult',
	  'whelcyliinderresult',
	  'generatorresult',
	  'brakerodresult',
	  'collsystresult',
	  'brakehoseresult',
	  'manifoldsresult',
	  'frontaxleresult',
	  'luberesult',
	  'shaftresult',
	  'prposhaftresult',
	  'axlehseresult',
	  'differential',
	  'tool',
	  'tyresize',
	  'jack',
	  'tyrecondition',
	  'puntrekit',
	  'tyreetc',
	  'headlamp',
	  'steerwheel',
	  'indicator',
	  'pstaring',
	  'rear',
	  'horn',
	  'brake',
	  'gauges',
	  'etc',
	  'climatecntrl',
	  'doorr',
	  'windowss',
	  'interiorr',
	  'wipers',
	  'exteriorr',
	  'mirrorrs',
	  'underbody',
	  'atmt',
	  'safbelts',
	  'brekpedal',
	  'radiationdose',
	  'brakeboost',
	  'clutcchpedal',
	  'clutchfunction',
	  'exhaustsyystem',
	  'airsuspenresult',
	  'airbreakkresult',
	  'fueltankkresult',
	  'file'
	];

	  public function vehicle()
	  {
	  	return $this->belongsTo('Vehicle','vehicle_id');
	  }
	
}